# Generated by Django 5.2.4 on 2025-07-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_customuser_groups_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_oauth_verified',
            field=models.BooleanField(default=False, verbose_name='OAuth Verified'),
        ),
    ]
