# Generated by Django 5.2.4 on 2025-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_livedocumentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedocumentuser',
            name='color',
            field=models.CharField(default='#F49AC2', max_length=7),
        ),
    ]
