# Generated by Django 5.2.4 on 2025-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_livedocumentuser_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livedocumentuser',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
