# Generated by Django 5.2.4 on 2025-07-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_livedocumentuser_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livedocumentuser',
            old_name='display_name',
            new_name='name',
        ),
    ]
