# Generated by Django 5.2.4 on 2025-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_rename_display_name_livedocumentuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedocumentuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
